### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by mhaas6** [neavo/KeywordGacha#34]
[2024-07-23 15:11:27] [INFO] 即将开始执行 [查找 NER 实体] ...
[2024-07-23 15:20:50] [INFO] [查找 NER 实体] 已完成 ...
[2024-07-23 15:20:51] [INFO] 即将开始执行 [查找上下文] ...
[2024-07-23 15:20:52] [INFO] [查找上下文] 已完成 ...
[2024-07-23 15:20:52] [INFO] 即将开始执行 [词根还原] ...
[2024-07-23 15:20:52] [INFO] 通过 [green]规则还原[/] 还原词根 - キュライア, キュライア訪問
[2024-07-23 15:20:52] [INFO] 通过 [green]规则还原[/] 还原词根 - 桃井いちご, 桃井いちご
[2024-07-23 15:20:52] [INFO] 通过 [green]规则还原[/] 还原词根 - 梅木ちはる, 梅木ちはる
[2024-07-23 15:20:52] [INFO] 通过 [green]规则还原[/] 还原词根 - 烏丸そら, 烏丸そら
[2024-07-23 15:20:52] [INFO] 通过 [green]规则还原[/] 还原词根 - 蒼依ハル, 蒼依ハル
[2024-07-23 15:20:52] [INFO] 通过 [green]规则还原[/] 还原词根 - 月野きいろ, 月野きいろ
[2024-07-23 15:20:52] [INFO] 通过 [green]规则还原[/] 还原词根 - 咲ゆたか, 咲ゆたか
[2024-07-23 15:20:52] [INFO] 通过 [green]规则还原[/] 还原词根 - まー安心シロ, まー安心シロ
[2024-07-23 15:20:52] [INFO] 通过 [green]规则还原[/] 还原词根 - 藍沢ちひろ, 藍沢ちひろ
[2024-07-23 15:20:52] [INFO] 通过 [green]规则还原[/] 还原词根 - 梅鳥うりり, 梅鳥うりり
[2024-07-23 15:20:52] [INFO] 通过 [green]规则还原[/] 还原词根 - 並木ユギ, 並木ユギ
[2024-07-23 15:20:52] [INFO] 通过 [green]规则还原[/] 还原词根 - 月白かんな, 月白かんな
[2024-07-23 15:20:52] [INFO] 通过 [green]规则还原[/] 还原词根 - 鳴海クリスティア, 鳴海クリスティア
[2024-07-23 15:20:52] [INFO] 通过 [green]规则还原[/] 还原词根 - 殿Дおふ, 殿Дおふ
[2024-07-23 15:20:52] [INFO] 通过 [green]出现次数[/] 还原词根 - ラシェンヌ, ラシェ
[2024-07-23 15:20:52] [INFO] 通过 [green]出现次数[/] 还原词根 - マルグレッテ, マルグレ
[2024-07-23 15:20:52] [INFO] 通过 [green]出现次数[/] 还原词根 - コルローネ, コルロ
[2024-07-23 15:20:52] [ERROR] division by zero
Traceback (most recent call last):
  File "F:\Download\KeywordGacha_DEV_20240720_143146\KeywordGacha\main.py", line 479, in main
    await begin()
  File "F:\Download\KeywordGacha_DEV_20240720_143146\KeywordGacha\main.py", line 391, in begin
    words = search_for_entity(ner, full_text_lines)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Download\KeywordGacha_DEV_20240720_143146\KeywordGacha\main.py", line 261, in search_for_entity
    words_person = ner.lemmatize_words_by_count(words_person)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Download\KeywordGacha_DEV_20240720_143146\KeywordGacha\model\NER.py", line 191, in lemmatize_words_by_count
    if abs(word.count - ex_word.count) / max(word.count, ex_word.count) > 0.05:
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
[2024-07-23 15:20:52] [ERROR] 出现严重错误，程序即将退出，错误信息已保存至日志文件 [green]KeywordGacha.log[/] ...
[2024-07-23 15:26:58] [INFO] 即将开始执行 [查找 NER 实体] ...
[2024-07-23 15:34:28] [INFO] [查找 NER 实体] 已完成 ...
[2024-07-23 15:34:28] [INFO] 即将开始执行 [查找上下文] ...
[2024-07-23 15:34:29] [INFO] [查找上下文] 已完成 ...
[2024-07-23 15:34:29] [INFO] 即将开始执行 [词根还原] ...
[2024-07-23 15:34:29] [INFO] 通过 [green]规则还原[/] 还原词根 - キュライア, キュライア訪問
[2024-07-23 15:34:29] [INFO] 通过 [green]规则还原[/] 还原词根 - 桃井いちご, 桃井いちご
[2024-07-23 15:34:29] [INFO] 通过 [green]规则还原[/] 还原词根 - 梅木ちはる, 梅木ちはる
[2024-07-23 15:34:29] [INFO] 通过 [green]规则还原[/] 还原词根 - 烏丸そら, 烏丸そら
[2024-07-23 15:34:29] [INFO] 通过 [green]规则还原[/] 还原词根 - 蒼依ハル, 蒼依ハル
[2024-07-23 15:34:29] [INFO] 通过 [green]规则还原[/] 还原词根 - 月野きいろ, 月野きいろ
[2024-07-23 15:34:29] [INFO] 通过 [green]规则还原[/] 还原词根 - 咲ゆたか, 咲ゆたか
[2024-07-23 15:34:29] [INFO] 通过 [green]规则还原[/] 还原词根 - 藍沢ちひろ, 藍沢ちひろ
[2024-07-23 15:34:29] [INFO] 通过 [green]规则还原[/] 还原词根 - 梅鳥うりり, 梅鳥うりり
[2024-07-23 15:34:29] [INFO] 通过 [green]规则还原[/] 还原词根 - 並木ユギ, 並木ユギ
[2024-07-23 15:34:29] [INFO] 通过 [green]规则还原[/] 还原词根 - 月白かんな, 月白かんな
[2024-07-23 15:34:29] [INFO] 通过 [green]规则还原[/] 还原词根 - 鳴海クリスティア, 鳴海クリスティア
[2024-07-23 15:34:29] [INFO] 通过 [green]出现次数[/] 还原词根 - ラシェンヌ, ラシェ
[2024-07-23 15:34:29] [INFO] 通过 [green]出现次数[/] 还原词根 - コルローネ, コルロ
[2024-07-23 15:34:29] [ERROR] division by zero
Traceback (most recent call last):
  File "F:\Download\KeywordGacha_DEV_20240720_143146\KeywordGacha\main.py", line 479, in main
    await begin()
  File "F:\Download\KeywordGacha_DEV_20240720_143146\KeywordGacha\main.py", line 391, in begin
    words = search_for_entity(ner, full_text_lines)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Download\KeywordGacha_DEV_20240720_143146\KeywordGacha\main.py", line 261, in search_for_entity
    words_person = ner.lemmatize_words_by_count(words_person)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Download\KeywordGacha_DEV_20240720_143146\KeywordGacha\model\NER.py", line 191, in lemmatize_words_by_count
    if abs(word.count - ex_word.count) / max(word.count, ex_word.count) > 0.05:
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
[2024-07-23 15:34:29] [ERROR] 出现严重错误，程序即将退出，错误信息已保存至日志文件 [green]KeywordGacha.log[/] ...

**Comment by mhaas6** [comment]
https://ufile.io/46acu8e9

测试文本

**Comment by neavo** [comment]
> https://ufile.io/46acu8e9
> 
> 测试文本

收到，稍后测试一下

看起来是因为 出现次数 = 0 导致的问题，你把设置里的 出现次数阈值 改为 0 了吗

**Comment by mhaas6** [comment]
> > https://ufile.io/46acu8e9
> > 测试文本
> 
> 收到，稍后测试一下
> 
> 看起来是因为 出现次数 = 0 导致的问题，你把设置里的 出现次数阈值 改为 0 了吗

    "count_threshold": 3,
    "request_timeout": 120,
    "request_frequency_threshold": 1,
    "translate_surface_mode": 1,
    "translate_context_mode": 1
}


没有设置为0

**Comment by neavo** [comment]
> if abs(word.count - ex_word.count) / max(word.count, ex_word.count)



> > > https://ufile.io/46acu8e9
> > > 测试文本
> > 
> > 
> > 收到，稍后测试一下
> > 看起来是因为 出现次数 = 0 导致的问题，你把设置里的 出现次数阈值 改为 0 了吗
> 
> ```
> "count_threshold": 3,
> "request_timeout": 120,
> "request_frequency_threshold": 1,
> "translate_surface_mode": 1,
> "translate_context_mode": 1
> ```
> 
> }
> 
> 没有设置为0

将压缩包内的 `NER.py` 覆盖 `model` 文件夹下的同名文件再试试

[NER.zip](https://github.com/user-attachments/files/16352084/NER.zip)
