### ISSUE TITLE
出现严重错误

### ISSUE THREAD

**Issue by Raiter123** [neavo/KeywordGacha#38]
出现严重错误,請問這是什麽
ZeroDivisionError: division by zero
[2024-07-26 18:12:13] [ERROR] 出现严重错误，程序即将退出，错误信息已保存至日志文件 [green]KeywordGacha.log[/] ...
[2024-07-26 19:06:11] [INFO] 即将开始执行 [查找 NER 实体] ...
[2024-07-26 19:14:13] [INFO] [查找 NER 实体] 已完成 ...
[2024-07-26 19:14:14] [INFO] 即将开始执行 [查找上下文] ...
[2024-07-26 19:14:16] [INFO] [查找上下文] 已完成 ...
[2024-07-26 19:14:16] [INFO] 即将开始执行 [词根还原] ...
[2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - 兄ぃ, 兄ぃ
[2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - 愛い, 愛い
[2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - 奈っちゃん, 奈っちゃん
[2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - ケント, ケント君
[2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - 金ちゃん, 金ちゃん
[2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - クソ, クソ女神
[2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - 奈っちゃんと, 奈っちゃんと
[2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - 一ノ, 一ノ瀬
[2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - 二ノ, 二ノ宮
[2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - 松○しげる, 松○しげる
[2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - 柏木レイリア, 柏木レイリア
[2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - 柏木ティア, 柏木ティア
[2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - 相田みつを, 相田みつを
[2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - 音埜クルミ, 音埜クルミ
[2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - モフモフ, モフモフ加減
[2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - コイツ, コイツ亜由美
[2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - フナムシ, フナムシ君
[2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - 東京上○クリニック, 東京上○クリニック
[2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - テメェ, テメェ宍戸
[2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - 今奈っちゃん, 今奈っちゃん
[2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - キングオブヘタレ, キングオブヘタレ章雄
[2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - 兎に, 兎に角茜
[2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - ななな, ななな奈
[2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - 当然ティア, 当然ティア
[2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - おい, おい裕哉
[2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - チャラ1, チャラ1号
[2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - ヘンリー8, ヘンリー8世
[2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - リチャード3, リチャード3世
[2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - エドワード5, エドワード5世
[2024-07-26 19:14:16] [INFO] 通过 [green]出现次数[/] 还原词根 - レイリ, レイ
[2024-07-26 19:14:16] [INFO] 通过 [green]出现次数[/] 还原词根 - レイリア, レイリ
[2024-07-26 19:14:16] [ERROR] division by zero
Traceback (most recent call last):
  File "E:\04_Software\關鍵名稱提取\main.py", line 479, in main
    await begin()
  File "E:\04_Software\關鍵名稱提取\main.py", line 391, in begin
    words = search_for_entity(ner, full_text_lines)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\04_Software\關鍵名稱提取\main.py", line 261, in search_for_entity
    words_person = ner.lemmatize_words_by_count(words_person)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\04_Software\關鍵名稱提取\model\NER.py", line 191, in lemmatize_words_by_count
    if abs(word.count - ex_word.count) / max(word.count, ex_word.count) > 0.05:
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
[2024-07-26 19:14:16] [ERROR] 出现严重错误，程序即将退出，错误信息已保存至日志文件 [green]KeywordGacha.log[/] ...

**Comment by neavo** [comment]
> 出现严重错误,請問這是什麽 ZeroDivisionError: division by zero [2024-07-26 18:12:13] [ERROR] 出现严重错误，程序即将退出，错误信息已保存至日志文件 [green]KeywordGacha.log[/] ... [2024-07-26 19:06:11] [INFO] 即将开始执行 [查找 NER 实体] ... [2024-07-26 19:14:13] [INFO] [查找 NER 实体] 已完成 ... [2024-07-26 19:14:14] [INFO] 即将开始执行 [查找上下文] ... [2024-07-26 19:14:16] [INFO] [查找上下文] 已完成 ... [2024-07-26 19:14:16] [INFO] 即将开始执行 [词根还原] ... [2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - 兄ぃ, 兄ぃ [2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - 愛い, 愛い [2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - 奈っちゃん, 奈っちゃん [2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - ケント, ケント君 [2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - 金ちゃん, 金ちゃん [2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - クソ, クソ女神 [2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - 奈っちゃんと, 奈っちゃんと [2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - 一ノ, 一ノ瀬 [2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - 二ノ, 二ノ宮 [2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - 松○しげる, 松○しげる [2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - 柏木レイリア, 柏木レイリア [2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - 柏木ティア, 柏木ティア [2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - 相田みつを, 相田みつを [2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - 音埜クルミ, 音埜クルミ [2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - モフモフ, モフモフ加減 [2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - コイツ, コイツ亜由美 [2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - フナムシ, フナムシ君 [2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - 東京上○クリニック, 東京上○クリニック [2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - テメェ, テメェ宍戸 [2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - 今奈っちゃん, 今奈っちゃん [2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - キングオブヘタレ, キングオブヘタレ章雄 [2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - 兎に, 兎に角茜 [2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - ななな, ななな奈 [2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - 当然ティア, 当然ティア [2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - おい, おい裕哉 [2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - チャラ1, チャラ1号 [2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - ヘンリー8, ヘンリー8世 [2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - リチャード3, リチャード3世 [2024-07-26 19:14:16] [INFO] 通过 [green]规则还原[/] 还原词根 - エドワード5, エドワード5世 [2024-07-26 19:14:16] [INFO] 通过 [green]出现次数[/] 还原词根 - レイリ, レイ [2024-07-26 19:14:16] [INFO] 通过 [green]出现次数[/] 还原词根 - レイリア, レイリ [2024-07-26 19:14:16] [ERROR] division by zero Traceback (most recent call last): File "E:\04_Software\關鍵名稱提取\main.py", line 479, in main await begin() File "E:\04_Software\關鍵名稱提取\main.py", line 391, in begin words = search_for_entity(ner, full_text_lines) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "E:\04_Software\關鍵名稱提取\main.py", line 261, in search_for_entity words_person = ner.lemmatize_words_by_count(words_person) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "E:\04_Software\關鍵名稱提取\model\NER.py", line 191, in lemmatize_words_by_count if abs(word.count - ex_word.count) / max(word.count, ex_word.count) > 0.05: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ZeroDivisionError: division by zero [2024-07-26 19:14:16] [ERROR] 出现严重错误，程序即将退出，错误信息已保存至日志文件 [green]KeywordGacha.log[/] ...

更新版本，0724 版本里已修复

https://github.com/neavo/KeywordGacha/releases/tag/MANAUL_BUILD_20240724_104208
