### ISSUE TITLE
某些中转无法使用

### ISSUE THREAD

**Issue by jeshs** [neavo/KeywordGacha#48]
1 使用某些中转接口报错，报错如下所示，但这些中转接口在 chatbox galtransl postman 等软件可以正常响应
```
[2024-08-11 10:09:56] [DEBUG] 'str' object has no attribute 'usage'
Traceback (most recent call last):
  File "D:\Portable\KeywordGacha_NV_0.1.0\KeywordGacha\model\LLM.py", line 167, in api_test
    usage, message, _ = await self.request(
                        ^^^^^^^^^^^^^^^^^^^
  File "D:\Portable\KeywordGacha_NV_0.1.0\KeywordGacha\model\LLM.py", line 156, in request
    usage = completion.usage
            ^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'usage'
[2024-08-11 10:09:56] [WARNING] 接口测试 [red]执行失败[/], 请检查配置文件 ...
```

2 这是使用 postman 调接口的正常请求和响应（隐去了api地址）
```
POST https://xxxx/api/v1/chat/completions HTTP/1.1
Content-Type: application/json
User-Agent: PostmanRuntime/7.29.5
Accept: */*
Postman-Token: e1b04f41-87cf-40e8-a16a-ef2af17aba69
Host: xxxx
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 411

{
    "messages": [
        {
            "role": "system",
            "content": "\nCurrent model: gpt-4o\nCurrent date: 2024-08-11T08:02:54.108Z\n\n你是一个智能助手，将会回答我的所有问题"
        },
        {
            "role": "user",
            "content": "你是谁"
        }
    ],
    "model": "gpt-4o",
    "temperature": 0.7,
    "top_p": 0.9,
    "stream": true
}



HTTP/1.1 200 OK
Date: Sun, 11 Aug 2024 08:02:56 GMT
Content-Type: text/event-stream; charset=utf-8
Connection: keep-alive
access-control-allow-origin: *
access-control-allow-headers: *
x-proxied-host: xxxx
x-proxied-path: /api/v1/chat/completions
link: <https://xxxx>;rel="canonical"
x-request-id: AO9jOL
vary: origin, access-control-request-method, access-control-request-headers
access-control-allow-credentials: true
Content-Length: 2781

data: {"id": "chatcmpl", "object": "chat.completion.chunk", "created": 1723363376, "model": "qwen1_5", "choices": [{"index": 0, "finish_reason": null, "delta": {"role": "assistant", "content": ""}}]}

data: {"id": "chatcmpl", "object": "chat.completion.chunk", "created": 1723363376, "model": "qwen1_5", "choices": [{"index": 0, "finish_reason": null, "delta": {"content": "\u6211\u662f"}}]}

data: {"id": "chatcmpl", "object": "chat.completion.chunk", "created": 1723363376, "model": "qwen1_5", "choices": [{"index": 0, "finish_reason": null, "delta": {"content": "\u6765\u81ea"}}]}

data: {"id": "chatcmpl", "object": "chat.completion.chunk", "created": 1723363376, "model": "qwen1_5", "choices": [{"index": 0, "finish_reason": null, "delta": {"content": "\u963f\u91cc"}}]}

data: {"id": "chatcmpl", "object": "chat.completion.chunk", "created": 1723363376, "model": "qwen1_5", "choices": [{"index": 0, "finish_reason": null, "delta": {"content": "\u4e91\u7684\u8d85\u5927\u89c4\u6a21\u8bed\u8a00"}}]}

data: {"id": "chatcmpl", "object": "chat.completion.chunk", "created": 1723363376, "model": "qwen1_5", "choices": [{"index": 0, "finish_reason": null, "delta": {"content": "\u6a21\u578b\uff0c\u6211\u53eb\u901a\u4e49\u5343\u95ee"}}]}

data: {"id": "chatcmpl", "object": "chat.completion.chunk", "created": 1723363376, "model": "qwen1_5", "choices": [{"index": 0, "finish_reason": null, "delta": {"content": "\u3002\u6211\u662f\u963f\u91cc\u4e91\u81ea\u4e3b\u7814\u53d1\u7684\u8d85\u5927\u89c4\u6a21"}}]}

data: {"id": "chatcmpl", "object": "chat.completion.chunk", "created": 1723363376, "model": "qwen1_5", "choices": [{"index": 0, "finish_reason": null, "delta": {"content": "\u8bed\u8a00\u6a21\u578b\uff0c\u4e5f\u80fd\u591f\u56de\u7b54\u95ee\u9898\u3001"}}]}

data: {"id": "chatcmpl", "object": "chat.completion.chunk", "created": 1723363376, "model": "qwen1_5", "choices": [{"index": 0, "finish_reason": null, "delta": {"content": "\u521b\u4f5c\u6587\u5b57\uff0c\u8fd8\u80fd\u8868\u8fbe\u89c2\u70b9\u3001\u64b0\u5199"}}]}

data: {"id": "chatcmpl", "object": "chat.completion.chunk", "created": 1723363376, "model": "qwen1_5", "choices": [{"index": 0, "finish_reason": null, "delta": {"content": "\u4ee3\u7801\u3002\u5982\u679c\u60a8\u6709\u4efb\u4f55\u95ee\u9898\u6216\u9700\u8981\u5e2e\u52a9"}}]}

data: {"id": "chatcmpl", "object": "chat.completion.chunk", "created": 1723363376, "model": "qwen1_5", "choices": [{"index": 0, "finish_reason": null, "delta": {"content": "\uff0c\u8bf7\u968f\u65f6\u544a\u8bc9\u6211\uff0c\u6211\u4f1a\u5c3d\u529b\u63d0\u4f9b\u652f\u6301"}}]}

data: {"id": "chatcmpl", "object": "chat.completion.chunk", "created": 1723363376, "model": "qwen1_5", "choices": [{"index": 0, "finish_reason": null, "delta": {"content": "\u3002"}}]}

data: [DONE]
```

**Comment by neavo** [comment]
> 1 使用某些中转接口报错，报错如下所示，但这些中转接口在 chatbox galtransl postman 等软件可以正常响应
> 
> ```
> [2024-08-11 10:09:56] [DEBUG] 'str' object has no attribute 'usage'
> Traceback (most recent call last):
>   File "D:\Portable\KeywordGacha_NV_0.1.0\KeywordGacha\model\LLM.py", line 167, in api_test
>     usage, message, _ = await self.request(
>                         ^^^^^^^^^^^^^^^^^^^
>   File "D:\Portable\KeywordGacha_NV_0.1.0\KeywordGacha\model\LLM.py", line 156, in request
>     usage = completion.usage
>             ^^^^^^^^^^^^^^^^
> AttributeError: 'str' object has no attribute 'usage'
> [2024-08-11 10:09:56] [WARNING] 接口测试 [red]执行失败[/], 请检查配置文件 ...
> ```
> 
> 2 这是使用 postman 调接口的正常请求和响应（隐去了api地址）
> 
> ```
> POST https://xxxx/api/v1/chat/completions HTTP/1.1
> Content-Type: application/json
> User-Agent: PostmanRuntime/7.29.5
> Accept: */*
> Postman-Token: e1b04f41-87cf-40e8-a16a-ef2af17aba69
> Host: xxxx
> Accept-Encoding: gzip, deflate, br
> Connection: keep-alive
> Content-Length: 411
> 
> {
>     "messages": [
>         {
>             "role": "system",
>             "content": "\nCurrent model: gpt-4o\nCurrent date: 2024-08-11T08:02:54.108Z\n\n你是一个智能助手，将会回答我的所有问题"
>         },
>         {
>             "role": "user",
>             "content": "你是谁"
>         }
>     ],
>     "model": "gpt-4o",
>     "temperature": 0.7,
>     "top_p": 0.9,
>     "stream": true
> }
> 
> 
> 
> HTTP/1.1 200 OK
> Date: Sun, 11 Aug 2024 08:02:56 GMT
> Content-Type: text/event-stream; charset=utf-8
> Connection: keep-alive
> access-control-allow-origin: *
> access-control-allow-headers: *
> x-proxied-host: xxxx
> x-proxied-path: /api/v1/chat/completions
> link: <https://xxxx>;rel="canonical"
> x-request-id: AO9jOL
> vary: origin, access-control-request-method, access-control-request-headers
> access-control-allow-credentials: true
> Content-Length: 2781
> 
> data: {"id": "chatcmpl", "object": "chat.completion.chunk", "created": 1723363376, "model": "qwen1_5", "choices": [{"index": 0, "finish_reason": null, "delta": {"role": "assistant", "content": ""}}]}
> 
> data: {"id": "chatcmpl", "object": "chat.completion.chunk", "created": 1723363376, "model": "qwen1_5", "choices": [{"index": 0, "finish_reason": null, "delta": {"content": "\u6211\u662f"}}]}
> 
> data: {"id": "chatcmpl", "object": "chat.completion.chunk", "created": 1723363376, "model": "qwen1_5", "choices": [{"index": 0, "finish_reason": null, "delta": {"content": "\u6765\u81ea"}}]}
> 
> data: {"id": "chatcmpl", "object": "chat.completion.chunk", "created": 1723363376, "model": "qwen1_5", "choices": [{"index": 0, "finish_reason": null, "delta": {"content": "\u963f\u91cc"}}]}
> 
> data: {"id": "chatcmpl", "object": "chat.completion.chunk", "created": 1723363376, "model": "qwen1_5", "choices": [{"index": 0, "finish_reason": null, "delta": {"content": "\u4e91\u7684\u8d85\u5927\u89c4\u6a21\u8bed\u8a00"}}]}
> 
> data: {"id": "chatcmpl", "object": "chat.completion.chunk", "created": 1723363376, "model": "qwen1_5", "choices": [{"index": 0, "finish_reason": null, "delta": {"content": "\u6a21\u578b\uff0c\u6211\u53eb\u901a\u4e49\u5343\u95ee"}}]}
> 
> data: {"id": "chatcmpl", "object": "chat.completion.chunk", "created": 1723363376, "model": "qwen1_5", "choices": [{"index": 0, "finish_reason": null, "delta": {"content": "\u3002\u6211\u662f\u963f\u91cc\u4e91\u81ea\u4e3b\u7814\u53d1\u7684\u8d85\u5927\u89c4\u6a21"}}]}
> 
> data: {"id": "chatcmpl", "object": "chat.completion.chunk", "created": 1723363376, "model": "qwen1_5", "choices": [{"index": 0, "finish_reason": null, "delta": {"content": "\u8bed\u8a00\u6a21\u578b\uff0c\u4e5f\u80fd\u591f\u56de\u7b54\u95ee\u9898\u3001"}}]}
> 
> data: {"id": "chatcmpl", "object": "chat.completion.chunk", "created": 1723363376, "model": "qwen1_5", "choices": [{"index": 0, "finish_reason": null, "delta": {"content": "\u521b\u4f5c\u6587\u5b57\uff0c\u8fd8\u80fd\u8868\u8fbe\u89c2\u70b9\u3001\u64b0\u5199"}}]}
> 
> data: {"id": "chatcmpl", "object": "chat.completion.chunk", "created": 1723363376, "model": "qwen1_5", "choices": [{"index": 0, "finish_reason": null, "delta": {"content": "\u4ee3\u7801\u3002\u5982\u679c\u60a8\u6709\u4efb\u4f55\u95ee\u9898\u6216\u9700\u8981\u5e2e\u52a9"}}]}
> 
> data: {"id": "chatcmpl", "object": "chat.completion.chunk", "created": 1723363376, "model": "qwen1_5", "choices": [{"index": 0, "finish_reason": null, "delta": {"content": "\uff0c\u8bf7\u968f\u65f6\u544a\u8bc9\u6211\uff0c\u6211\u4f1a\u5c3d\u529b\u63d0\u4f9b\u652f\u6301"}}]}
> 
> data: {"id": "chatcmpl", "object": "chat.completion.chunk", "created": 1723363376, "model": "qwen1_5", "choices": [{"index": 0, "finish_reason": null, "delta": {"content": "\u3002"}}]}
> 
> data: [DONE]
> ```

我想确认一下，是这个中转的所有模型都无法在KG使用，还是只是某些特定模型不行，如果是后者，那么具体是哪些模型不行，哪些模型可以？

**Comment by jeshs** [comment]
1 这是单个模型的中转。我问了AI, AI 建议在LLM.py 的 request 函数和  api_test 函数加一些日志代码
```
async def request(self, content, task_type, retry=False):
    try:
        completion = await self.openai_handler.chat.completions.create(
            model=self.model_name,
            temperature=self.LLMCONFIG[task_type].TEMPERATURE,
            top_p=self.LLMCONFIG[task_type].TOP_P,
            max_tokens=self.LLMCONFIG[task_type].MAX_TOKENS,
            frequency_penalty=self.LLMCONFIG[task_type].FREQUENCY_PENALTY + 0.2 if retry else self.LLMCONFIG[task_type].FREQUENCY_PENALTY,
            messages=[
                {
                    "role": "user", 
                    "content": content
                },
            ],
        )
        
        LogHelper.debug(f"API Response: {completion}")
        
        usage = completion.usage
        message = completion.choices[0].message

        return usage, message, completion
    except Exception as e:
        LogHelper.error(f"Error in API request: {str(e)}")
        LogHelper.debug(f"Full traceback: {LogHelper.get_trackback(e)}")
        raise

async def api_test(self):
    async with self.semaphore, self.async_limiter:
        result = True

        try:
            LogHelper.info("Starting API test...")
            
            usage, message, full_response = await self.request(
                self.prompt_translate_surface_person.replace("{attribute}", "女性").replace("{surface}", "ダリヤ").replace("{context}", "ダリヤ"),
                self.TASK_TYPE_API_TEST,
                True
            )

            LogHelper.info(f"API test completed. Full response: {full_response}")
            LogHelper.info(f"Usage: {usage}")
            LogHelper.info(f"Message content: {message.content}")

            if usage.completion_tokens >= self.LLMCONFIG[self.TASK_TYPE_API_TEST].MAX_TOKENS:
                raise Exception("usage.completion_tokens >= MAX_TOKENS")                
        
            data = json.loads(
                TextHelper.fix_broken_json_string(message.content.strip())
            )
            LogHelper.info(f"Parsed data: {data}")
        except json.JSONDecodeError as je:
            result = False
            LogHelper.error(f"JSON parsing error: {str(je)}")
            LogHelper.debug(f"Raw content that failed to parse: {message.content.strip()}")
        except Exception as e:
            result = False
            LogHelper.error(f"API test failed: {str(e)}")
            LogHelper.debug(f"Full traceback: {LogHelper.get_trackback(e)}")
        
        return result
```
2 再次运行后，KeywordGacha.log 输出日志如下。可以看到接口返回是成功的
```
[2024-08-11 22:02:16] [INFO] Starting API test...
[2024-08-11 22:02:21] [DEBUG] API Response: data: {"id": "chatcmpl", "object": "chat.completion.chunk", "created": 1723384937, "model": "qwen1_5", "choices": [{"index": 0, "finish_reason": null, "delta": {"role": "assistant", "content": ""}}]}

data: {"id": "chatcmpl", "object": "chat.completion.chunk", "created": 1723384937, "model": "qwen1_5", "choices": [{"index": 0, "finish_reason": null, "delta": {"content": "{"}}]}

data: {"id": "chatcmpl", "object": "chat.completion.chunk", "created": 1723384937, "model": "qwen1_5", "choices": [{"index": 0, "finish_reason": null, "delta": {"content": "\n\""}}]}

data: {"id": "chatcmpl", "object": "chat.completion.chunk", "created": 1723384937, "model": "qwen1_5", "choices": [{"index": 0, "finish_reason": null, "delta": {"content": "translation"}}]}

data: {"id": "chatcmpl", "object": "chat.completion.chunk", "created": 1723384937, "model": "qwen1_5", "choices": [{"index": 0, "finish_reason": null, "delta": {"content": "_1\": \"\u8fbe"}}]}

data: {"id": "chatcmpl", "object": "chat.completion.chunk", "created": 1723384937, "model": "qwen1_5", "choices": [{"index": 0, "finish_reason": null, "delta": {"content": "\u8389\u5a05\",\n\"translation_2\":"}}]}

data: {"id": "chatcmpl", "object": "chat.completion.chunk", "created": 1723384937, "model": "qwen1_5", "choices": [{"index": 0, "finish_reason": null, "delta": {"content": " \"\u9edb\u8389\u96c5\",\n\"romaji"}}]}

data: {"id": "chatcmpl", "object": "chat.completion.chunk", "created": 1723384937, "model": "qwen1_5", "choices": [{"index": 0, "finish_reason": null, "delta": {"content": "\": \"Dariya\",\n\"description\":"}}]}

data: {"id": "chatcmpl", "object": "chat.completion.chunk", "created": 1723384937, "model": "qwen1_5", "choices": [{"index": 0, "finish_reason": null, "delta": {"content": " \"\u89d2\u8272\u540d\u7ffb\u8bd1\"\n}"}}]}

data: [DONE]
[2024-08-11 22:02:21] [ERROR] Error in API request: 'str' object has no attribute 'usage'
[2024-08-11 22:02:21] [DEBUG] Full traceback: 'str' object has no attribute 'usage'
Traceback (most recent call last):
  File "D:\Portable\KeywordGacha_NV_0.1.0\KeywordGacha\model\LLM.py", line 158, in request
    usage = completion.usage
            ^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'usage'
[2024-08-11 22:02:21] [ERROR] API test failed: 'str' object has no attribute 'usage'
[2024-08-11 22:02:21] [DEBUG] Full traceback: 'str' object has no attribute 'usage'
Traceback (most recent call last):
  File "D:\Portable\KeywordGacha_NV_0.1.0\KeywordGacha\model\LLM.py", line 177, in api_test
    usage, message, full_response = await self.request(
                                    ^^^^^^^^^^^^^^^^^^^
  File "D:\Portable\KeywordGacha_NV_0.1.0\KeywordGacha\model\LLM.py", line 158, in request
    usage = completion.usage
            ^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'usage'
[2024-08-11 22:02:21] [WARNING] 接口测试 [red]执行失败[/], 请检查配置文件 ...

```

3 然后 AI 说是接口返回的格式问题，不过这里我也不懂了，下面是AI的回复
```
感谢您提供了详细的错误信息。从错误日志中我们可以看出，问题出在 API 返回的结果格式上。看起来您使用的 API（可能是 Qwen 模型）返回的是流式响应（stream response），而不是我们预期的完整响应对象。让我们修改代码以适应这种情况：

首先，在 request 方法中，我们需要处理流式响应：

pythonCopyasync def request(self, content, task_type, retry=False):
    try:
        stream = await self.openai_handler.chat.completions.create(
            model=self.model_name,
            temperature=self.LLMCONFIG[task_type].TEMPERATURE,
            top_p=self.LLMCONFIG[task_type].TOP_P,
            max_tokens=self.LLMCONFIG[task_type].MAX_TOKENS,
            frequency_penalty=self.LLMCONFIG[task_type].FREQUENCY_PENALTY + 0.2 if retry else self.LLMCONFIG[task_type].FREQUENCY_PENALTY,
            messages=[
                {
                    "role": "user", 
                    "content": content
                },
            ],
            stream=True  # 启用流式响应
        )
        
        full_response = ""
        async for chunk in stream:
            if chunk.choices[0].delta.content is not None:
                full_response += chunk.choices[0].delta.content
            LogHelper.debug(f"Chunk received: {chunk}")
        
        LogHelper.debug(f"Full response: {full_response}")
        
        # 由于是流式响应，我们没有 usage 信息，所以返回 None
        return None, type('obj', (object,), {'content': full_response})(), full_response
    except Exception as e:
        LogHelper.error(f"Error in API request: {str(e)}")
        LogHelper.debug(f"Full traceback: {LogHelper.get_trackback(e)}")
        raise

然后，在 api_test 方法中，我们需要适应这种变化：

pythonCopyasync def api_test(self):
    async with self.semaphore, self.async_limiter:
        result = True

        try:
            LogHelper.info("Starting API test...")
            
            usage, message, full_response = await self.request(
                self.prompt_translate_surface_person.replace("{attribute}", "女性").replace("{surface}", "ダリヤ").replace("{context}", "ダリヤ"),
                self.TASK_TYPE_API_TEST,
                True
            )

            LogHelper.info(f"API test completed. Full response: {full_response}")
            LogHelper.info(f"Message content: {message.content}")

            # 由于我们没有 usage 信息，所以跳过这个检查
            # if usage.completion_tokens >= self.LLMCONFIG[self.TASK_TYPE_API_TEST].MAX_TOKENS:
            #     raise Exception("usage.completion_tokens >= MAX_TOKENS")                
        
            data = json.loads(
                TextHelper.fix_broken_json_string(message.content.strip())
            )
            LogHelper.info(f"Parsed data: {data}")
        except json.JSONDecodeError as je:
            result = False
            LogHelper.error(f"JSON parsing error: {str(je)}")
            LogHelper.debug(f"Raw content that failed to parse: {message.content.strip()}")
        except Exception as e:
            result = False
            LogHelper.error(f"API test failed: {str(e)}")
            LogHelper.debug(f"Full traceback: {LogHelper.get_trackback(e)}")
        
        return result
这些修改应该能解决您遇到的问题。主要的变化是：

我们现在处理流式响应，逐块接收并拼接完整的响应。
由于流式响应没有提供 usage 信息，我们跳过了相关的检查。
我们创建了一个简单的对象来模拟原来的 message 对象，保持接口的一致性。

请尝试这些修改，看看是否能解决您的问题。如果还有任何问题，请随时告诉我，我会很乐意继续帮助您。
```

**Comment by neavo** [comment]
这个中转平台是你自己搭的吗，如果是的话，感觉你用错模板了

这个回复并不是一个标准的 OpenAI 接口回复格式，标准的 OpenAI 接口应该是类似这样的：

```json
{
    "id" : "...",
    "model" : "glm-4-9b-chat",
    "usage" : {
        "total_tokens" : 999,
        "prompt_tokens" : 999,
        "completion_tokens" : 999
    },
    "choices" : [
        {
            "message" : {
                "content" : '{\n"summary": "内容中提到\'オルランド\'一词，涉及商业交易、个人关系和职业背景。首先，\'オルランド\'被提及为与另一人共同名义的银行账户持有人。其次，\'オルランド\'被提及为某人的前婚约对象，且在商业活动中扮演重要角色。最后，\'オルランド\'被描述为某个商会的成员，负责魔導具的开发和销售。",\n"basis": "根据内容，\'オルランド\'多次作为个人名称出现，且与具体的人物和事件相关联。",\n"is_name": "是",\n"sex": "男"\n}',
            },
            "finish_reason" : "stop"
        }
    ]
}
```

**Comment by jeshs** [comment]
这是openai的流式请求，参考文档：https://platform.openai.com/docs/api-reference/streaming

**Comment by neavo** [comment]
> 这是openai的流式请求，参考文档：https://platform.openai.com/docs/api-reference/streaming

原来是这样，还真没认真看过流式输出的文档

因为无论如何都得等数据返回完才能开始处理，流式输出的即时性没什么意义，反而会降低性能

不过很奇怪，因为默认应该就是非流式输出才对，为什么你这个接口默认是流式输出

试试显式的关闭流式输出，看看能不能解决问题

在 `LLM.py` 第 141 行左右

```python
        completion = await self.openai_handler.chat.completions.create(
            model = self.model_name,
            stream = False, # 这里增加一行
            temperature = self.LLMCONFIG[task_type].TEMPERATURE,
            top_p = self.LLMCONFIG[task_type].TOP_P,
            max_tokens = self.LLMCONFIG[task_type].MAX_TOKENS,
            frequency_penalty = self.LLMCONFIG[task_type].FREQUENCY_PENALTY + 0.2 if retry else self.LLMCONFIG[task_type].FREQUENCY_PENALTY,
            messages = [
                {
                    "role": "user", 
                    "content": content
                },
            ],
        )

```

**Comment by jeshs** [comment]
返回流式是因为这些 API 是薅的那些聊天接口，而聊天接口普遍是流式的。我在AI的帮助下修改测试成功了，可以参考做兼容处理，对于流式返回的内容采用不同的处理方式
```
async def request(self, content, task_type, retry=False):
    try:
        completion = await self.openai_handler.chat.completions.create(
            model=self.model_name,
            temperature=self.LLMCONFIG[task_type].TEMPERATURE,
            top_p=self.LLMCONFIG[task_type].TOP_P,
            max_tokens=self.LLMCONFIG[task_type].MAX_TOKENS,
            frequency_penalty=self.LLMCONFIG[task_type].FREQUENCY_PENALTY + 0.2 if retry else self.LLMCONFIG[task_type].FREQUENCY_PENALTY,
            messages=[
                {
                    "role": "user", 
                    "content": content
                },
            ],
            stream=True  # 始终使用流式数据
        )
        
        LogHelper.debug(f"API Response: {completion}")
        
        full_response = ""
        async for chunk in completion:
            if isinstance(chunk, str):
                # 如果chunk是字符串，直接添加
                full_response += chunk
            elif hasattr(chunk, 'choices') and chunk.choices:
                # 如果chunk是对象，提取content
                if chunk.choices[0].delta.content is not None:
                    full_response += chunk.choices[0].delta.content

        # 解析完整的响应
        try:
            response_json = json.loads(full_response)
        except json.JSONDecodeError:
            # 如果不是有效的JSON，就使用原始字符串
            response_json = {"content": full_response}

        # 构造一个模拟的响应对象
        class MockCompletion:
            def __init__(self, content):
                self.choices = [type('obj', (object,), {'message': type('obj', (object,), {'content': content})()})()]
                self.usage = type('obj', (object,), {'completion_tokens': len(content), 'prompt_tokens': len(content), 'total_tokens': 2*len(content)})()

        mock_completion = MockCompletion(response_json.get('content', full_response))
        
        usage = mock_completion.usage
        message = mock_completion.choices[0].message

        return usage, message, mock_completion
    except Exception as e:
        LogHelper.error(f"Error in API request: {str(e)}")
        LogHelper.debug(f"Full traceback: {LogHelper.get_trackback(e)}")
        raise
在这个版本中，我们：

始终将 stream 设置为 True。
处理两种可能的chunk类型：字符串和对象。
尝试将完整的响应解析为JSON，如果失败则使用原始字符串。
创建一个模拟的完成对象，包含所需的 usage 和 message 属性。
```

**Comment by neavo** [comment]
> 返回流式是因为这些 API 是薅的那些聊天接口，而聊天接口普遍是流式的。我在AI的帮助下修改测试成功了，可以参考做兼容处理，对于流式返回的内容采用不同的处理方式
> 
> ```
> async def request(self, content, task_type, retry=False):
>     try:
>         completion = await self.openai_handler.chat.completions.create(
>             model=self.model_name,
>             temperature=self.LLMCONFIG[task_type].TEMPERATURE,
>             top_p=self.LLMCONFIG[task_type].TOP_P,
>             max_tokens=self.LLMCONFIG[task_type].MAX_TOKENS,
>             frequency_penalty=self.LLMCONFIG[task_type].FREQUENCY_PENALTY + 0.2 if retry else self.LLMCONFIG[task_type].FREQUENCY_PENALTY,
>             messages=[
>                 {
>                     "role": "user", 
>                     "content": content
>                 },
>             ],
>             stream=True  # 始终使用流式数据
>         )
>         
>         LogHelper.debug(f"API Response: {completion}")
>         
>         full_response = ""
>         async for chunk in completion:
>             if isinstance(chunk, str):
>                 # 如果chunk是字符串，直接添加
>                 full_response += chunk
>             elif hasattr(chunk, 'choices') and chunk.choices:
>                 # 如果chunk是对象，提取content
>                 if chunk.choices[0].delta.content is not None:
>                     full_response += chunk.choices[0].delta.content
> 
>         # 解析完整的响应
>         try:
>             response_json = json.loads(full_response)
>         except json.JSONDecodeError:
>             # 如果不是有效的JSON，就使用原始字符串
>             response_json = {"content": full_response}
> 
>         # 构造一个模拟的响应对象
>         class MockCompletion:
>             def __init__(self, content):
>                 self.choices = [type('obj', (object,), {'message': type('obj', (object,), {'content': content})()})()]
>                 self.usage = type('obj', (object,), {'completion_tokens': len(content), 'prompt_tokens': len(content), 'total_tokens': 2*len(content)})()
> 
>         mock_completion = MockCompletion(response_json.get('content', full_response))
>         
>         usage = mock_completion.usage
>         message = mock_completion.choices[0].message
> 
>         return usage, message, mock_completion
>     except Exception as e:
>         LogHelper.error(f"Error in API request: {str(e)}")
>         LogHelper.debug(f"Full traceback: {LogHelper.get_trackback(e)}")
>         raise
> 在这个版本中，我们：
> 
> 始终将 stream 设置为 True。
> 处理两种可能的chunk类型：字符串和对象。
> 尝试将完整的响应解析为JSON，如果失败则使用原始字符串。
> 创建一个模拟的完成对象，包含所需的 usage 和 message 属性。
> ```

支持流式输出很简单，但是这会提高代码的维护成本，所以我没有计划对流式输出进行官方的支持

好在这是开源项目，你可以自己动手随意进行你喜欢的修改 ：）

不过在DS只要几毛钱的今天，个人并不推荐使用这种逆向破解接口，因为输出很不稳定，浪费时间

**Comment by SerDavil** [comment]
请问一下，现在怎么修改可以支持流式呢？？我改了半天头都麻了💔
