### ISSUE TITLE
[语义分析] 子任务执行失败后是否会无限次重试？

### ISSUE THREAD

**Issue by kunger97** [neavo/KeywordGacha#60]
请问 [语义分析] 子任务执行失败 后是否可以限制重试次数？目前测试似乎会无限次重试该子任务。假如改子任务存在导致模型退化的关键字，会导致任务一直执行？

附上一部分错误日志
```
[2024-09-26 17:59:53] [DEBUG] llm_request - {'model': 'Qwen2.5-32B', 'stream': False, 'temperature': 0.05, 'top_p': 0.85, 'max_tokens': 768, 'frequency_penalty': 0, 'messages': [{'role': 'user', 'content': '你是一位文本分析和语言学专家，擅长从文本中提取关键词语，并对其词性和含义进行分析。\n请按步骤对以下文本进行总结与分析。\n\n步骤：\n1、目标词语：斉藤。\n2、故事总结：逐句阅读所有文本，总结与目标词语相关的故事内容。\n3、词义分析：在文本中找到目标词语出现的每一个地方，结合上下文，分析其词性、语义、指代实体或概念等语言学信息。\n4、姓名判断：根据语言学知识和故事总结、词义分析的结果，对目标词语中是否包含角色、家族或生物的名称进行判断，不能确定时默认为"未知"。请注意，如果目标词语是用于描述头衔、职业、亲属关系等人物属性的词语，那么即使该词语指代一个角色、家族或生物，也应判断为"否"。\n\n文本：\n「あの文化祭での乱交、要はウチらの担任を解雇にするための口実にも利用されてたんだよね。クラスメートの半数を巻き込んでさ。結果的に斉藤先生は『先生』の思惑通りに『身代わり』にされて学校から居なくなっちゃったけど。まぁ、斉藤先生の場合は自業自得だからクビにされたのは別段気にしてないけどさ。やっぱり不満は出るよね。理不尽なことは特に」\nゆいなが風邪で欠席した初日の朝、担任の口から告げられたD組の担任である斉藤教員による学園資金の私的流用の知らせに俺は耳を疑った。\nなんでも斉藤先生は学校への寄付金や運営資金などのお金の流れを一任されていたらしく、その業務を私的流用していたとのことだ。\n斉藤先生の横領事件の報せは瞬く間に学園中を駆け巡り、保護者説明会も立ち見が出るほど盛況だったらしい。\n\n回答使用中文，JSON格式，仅需要以下数据，不要添加额外的文字、说明或注释：\n{\n"summary":"<故事总结步骤的结果>",\n"analysis":"<词义分析步骤的结果>",\n"reason":"<姓名判断步骤的依据>",\n"is_name":"<姓名判断步骤的结果：是/否/未知>",\n"gender":"<性别判断的结果：男/女/未知>"\n}'}]}
[2024-09-26 17:59:53] [DEBUG] llm_response - None
[2024-09-26 17:59:54] [WARNING] [语义分析] 子任务执行失败，稍后将重试 ... Error code: 400
Traceback (most recent call last):
  File "F:\KeywordGacha\model\LLM.py", line 397, in summarize_context
    raise error
  File "F:\KeywordGacha\model\LLM.py", line 140, in request
    completion = await self.openai_handler.chat.completions.create(**llm_request)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\KeywordGacha\env\Lib\site-packages\openai\resources\chat\completions.py", line 1412, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
  File "F:\KeywordGacha\env\Lib\site-packages\openai\_base_client.py", line 1829, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\KeywordGacha\env\Lib\site-packages\openai\_base_client.py", line 1523, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "F:\KeywordGacha\env\Lib\site-packages\openai\_base_client.py", line 1624, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400
[2024-09-26 17:59:54] [DEBUG] llm_request - {'model': 'Qwen2.5-32B', 'stream': False, 'temperature': 0.05, 'top_p': 0.85, 'max_tokens': 768, 'frequency_penalty': 0, 'messages': [{'role': 'user', 'content': '你是一位文本分析和语言学专家，擅长从文本中提取关键词语，并对其词性和含义进行分析。\n请按步骤对以下文本进行总结与分析。\n\n步骤：\n1、目标词语：吉田。\n2、故事总结：逐句阅读所有文本，总结与目标词语相关的故事内容。\n3、词义分析：在文本中找到目标词语出现的每一个地方，结合上下文，分析其词性、语义、指代实体或概念等语言学信息。\n4、姓名判断：根据语言学知识和故事总结、词义分析的结果，对目标词语中是否包含角色、家族或生物的名称进行判断，不能确定时默认为"未知"。请注意，如果目标词语是用于描述头衔、职业、亲属关系等人物属性的词语，那么即使该词语指代一个角色、家族或生物，也应判断为"否"。\n\n文本：\n「えー、本日の夜に保護者説明会と緊急職員会議が開かれることになりました。詳しい話は今日の放課後に学年主任である吉田先生から説明がありますので、それまでは静かに待つ様にしてください。くれぐれもSNSで情報を拡散しないよう留意してください」\nそして姉は学園内にある不自然な間取りと空白の区画の存在に気が付いた。気が付いてしまったから吉田の標的にされてしまった。\nこの段階で朝日山ゆいなが黒幕である吉田の犯罪行為に加担している裏切り者であるのは誰の目から見ても明白である。\nこれが吉田のやり方なのか。\n\n回答使用中文，JSON格式，仅需要以下数据，不要添加额外的文字、说明或注释：\n{\n"summary":"<故事总结步骤的结果>",\n"analysis":"<词义分析步骤的结果>",\n"reason":"<姓名判断步骤的依据>",\n"is_name":"<姓名判断步骤的结果：是/否/未知>",\n"gender":"<性别判断的结果：男/女/未知>"\n}'}]}
[2024-09-26 17:59:54] [DEBUG] llm_response - None
[2024-09-26 17:59:56] [WARNING] [语义分析] 子任务执行失败，稍后将重试 ... Error code: 400
Traceback (most recent call last):
  File "F:\KeywordGacha\model\LLM.py", line 397, in summarize_context
    raise error
  File "F:\KeywordGacha\model\LLM.py", line 140, in request
    completion = await self.openai_handler.chat.completions.create(**llm_request)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\KeywordGacha\env\Lib\site-packages\openai\resources\chat\completions.py", line 1412, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
  File "F:\KeywordGacha\env\Lib\site-packages\openai\_base_client.py", line 1829, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\KeywordGacha\env\Lib\site-packages\openai\_base_client.py", line 1523, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "F:\KeywordGacha\env\Lib\site-packages\openai\_base_client.py", line 1624, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400
[2024-09-26 17:59:56] [DEBUG] llm_request - {'model': 'Qwen2.5-32B', 'stream': False, 'temperature': 0.05, 'top_p': 0.85, 'max_tokens': 768, 'frequency_penalty': 0, 'messages': [{'role': 'user', 'content': '你是一位文本分析和语言学专家，擅长从文本中提取关键词语，并对其词性和含义进行分析。\n请按步骤对以下文本进行总结与分析。\n\n步骤：\n1、目标词语：天海彼方。\n2、故事总结：逐句阅读所有文本，总结与目标词语相关的故事内容。\n3、词义分析：在文本中找到目标词语出现的每一个地方，结合上下文，分析其词性、语义、指代实体或概念等语言学信息。\n4、姓名判断：根据语言学知识和故事总结、词义分析的结果，对目标词语中是否包含角色、家族或生物的名称进行判断，不能确定时默认为"未知"。请注意，如果目标词语是用于描述头衔、职业、亲属关系等人物属性的词语，那么即使该词语指代一个角色、家族或生物，也应判断为"否"。\n\n文本：\n俺は自身の軽率な行動を後悔した。そして同時に天海彼方という女に対する恐怖心がさらに増した。\n「リディアちゃんと同じクラスの一年A組の天海彼方です。よろしくお願いします。夕凪先輩」\nそんなアリサを横目に俺は一年A組の天海彼方の名前を脳髄に刻み込む。\n天海彼方と名乗る一年生女子はアリサに深々と頭を下げた。\n\n回答使用中文，JSON格式，仅需要以下数据，不要添加额外的文字、说明或注释：\n{\n"summary":"<故事总结步骤的结果>",\n"analysis":"<词义分析步骤的结果>",\n"reason":"<姓名判断步骤的依据>",\n"is_name":"<姓名判断步骤的结果：是/否/未知>",\n"gender":"<性别判断的结果：男/女/未知>"\n}'}]}
[2024-09-26 17:59:56] [DEBUG] llm_response - None

```

**Comment by neavo** [comment]
> 请问 [语义分析] 子任务执行失败 后是否可以限制重试次数？目前测试似乎会无限次重试该子任务。假如改子任务存在导致模型退化的关键字，会导致任务一直执行？
> 
> 附上一部分错误日志
> 
> ```
> [2024-09-26 17:59:53] [DEBUG] llm_request - {'model': 'Qwen2.5-32B', 'stream': False, 'temperature': 0.05, 'top_p': 0.85, 'max_tokens': 768, 'frequency_penalty': 0, 'messages': [{'role': 'user', 'content': '你是一位文本分析和语言学专家，擅长从文本中提取关键词语，并对其词性和含义进行分析。\n请按步骤对以下文本进行总结与分析。\n\n步骤：\n1、目标词语：斉藤。\n2、故事总结：逐句阅读所有文本，总结与目标词语相关的故事内容。\n3、词义分析：在文本中找到目标词语出现的每一个地方，结合上下文，分析其词性、语义、指代实体或概念等语言学信息。\n4、姓名判断：根据语言学知识和故事总结、词义分析的结果，对目标词语中是否包含角色、家族或生物的名称进行判断，不能确定时默认为"未知"。请注意，如果目标词语是用于描述头衔、职业、亲属关系等人物属性的词语，那么即使该词语指代一个角色、家族或生物，也应判断为"否"。\n\n文本：\n「あの文化祭での乱交、要はウチらの担任を解雇にするための口実にも利用されてたんだよね。クラスメートの半数を巻き込んでさ。結果的に斉藤先生は『先生』の思惑通りに『身代わり』にされて学校から居なくなっちゃったけど。まぁ、斉藤先生の場合は自業自得だからクビにされたのは別段気にしてないけどさ。やっぱり不満は出るよね。理不尽なことは特に」\nゆいなが風邪で欠席した初日の朝、担任の口から告げられたD組の担任である斉藤教員による学園資金の私的流用の知らせに俺は耳を疑った。\nなんでも斉藤先生は学校への寄付金や運営資金などのお金の流れを一任されていたらしく、その業務を私的流用していたとのことだ。\n斉藤先生の横領事件の報せは瞬く間に学園中を駆け巡り、保護者説明会も立ち見が出るほど盛況だったらしい。\n\n回答使用中文，JSON格式，仅需要以下数据，不要添加额外的文字、说明或注释：\n{\n"summary":"<故事总结步骤的结果>",\n"analysis":"<词义分析步骤的结果>",\n"reason":"<姓名判断步骤的依据>",\n"is_name":"<姓名判断步骤的结果：是/否/未知>",\n"gender":"<性别判断的结果：男/女/未知>"\n}'}]}
> [2024-09-26 17:59:53] [DEBUG] llm_response - None
> [2024-09-26 17:59:54] [WARNING] [语义分析] 子任务执行失败，稍后将重试 ... Error code: 400
> Traceback (most recent call last):
>   File "F:\KeywordGacha\model\LLM.py", line 397, in summarize_context
>     raise error
>   File "F:\KeywordGacha\model\LLM.py", line 140, in request
>     completion = await self.openai_handler.chat.completions.create(**llm_request)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "F:\KeywordGacha\env\Lib\site-packages\openai\resources\chat\completions.py", line 1412, in create
>     return await self._post(
>            ^^^^^^^^^^^^^^^^^
>   File "F:\KeywordGacha\env\Lib\site-packages\openai\_base_client.py", line 1829, in post
>     return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "F:\KeywordGacha\env\Lib\site-packages\openai\_base_client.py", line 1523, in request
>     return await self._request(
>            ^^^^^^^^^^^^^^^^^^^^
>   File "F:\KeywordGacha\env\Lib\site-packages\openai\_base_client.py", line 1624, in _request
>     raise self._make_status_error_from_response(err.response) from None
> openai.BadRequestError: Error code: 400
> [2024-09-26 17:59:54] [DEBUG] llm_request - {'model': 'Qwen2.5-32B', 'stream': False, 'temperature': 0.05, 'top_p': 0.85, 'max_tokens': 768, 'frequency_penalty': 0, 'messages': [{'role': 'user', 'content': '你是一位文本分析和语言学专家，擅长从文本中提取关键词语，并对其词性和含义进行分析。\n请按步骤对以下文本进行总结与分析。\n\n步骤：\n1、目标词语：吉田。\n2、故事总结：逐句阅读所有文本，总结与目标词语相关的故事内容。\n3、词义分析：在文本中找到目标词语出现的每一个地方，结合上下文，分析其词性、语义、指代实体或概念等语言学信息。\n4、姓名判断：根据语言学知识和故事总结、词义分析的结果，对目标词语中是否包含角色、家族或生物的名称进行判断，不能确定时默认为"未知"。请注意，如果目标词语是用于描述头衔、职业、亲属关系等人物属性的词语，那么即使该词语指代一个角色、家族或生物，也应判断为"否"。\n\n文本：\n「えー、本日の夜に保護者説明会と緊急職員会議が開かれることになりました。詳しい話は今日の放課後に学年主任である吉田先生から説明がありますので、それまでは静かに待つ様にしてください。くれぐれもSNSで情報を拡散しないよう留意してください」\nそして姉は学園内にある不自然な間取りと空白の区画の存在に気が付いた。気が付いてしまったから吉田の標的にされてしまった。\nこの段階で朝日山ゆいなが黒幕である吉田の犯罪行為に加担している裏切り者であるのは誰の目から見ても明白である。\nこれが吉田のやり方なのか。\n\n回答使用中文，JSON格式，仅需要以下数据，不要添加额外的文字、说明或注释：\n{\n"summary":"<故事总结步骤的结果>",\n"analysis":"<词义分析步骤的结果>",\n"reason":"<姓名判断步骤的依据>",\n"is_name":"<姓名判断步骤的结果：是/否/未知>",\n"gender":"<性别判断的结果：男/女/未知>"\n}'}]}
> [2024-09-26 17:59:54] [DEBUG] llm_response - None
> [2024-09-26 17:59:56] [WARNING] [语义分析] 子任务执行失败，稍后将重试 ... Error code: 400
> Traceback (most recent call last):
>   File "F:\KeywordGacha\model\LLM.py", line 397, in summarize_context
>     raise error
>   File "F:\KeywordGacha\model\LLM.py", line 140, in request
>     completion = await self.openai_handler.chat.completions.create(**llm_request)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "F:\KeywordGacha\env\Lib\site-packages\openai\resources\chat\completions.py", line 1412, in create
>     return await self._post(
>            ^^^^^^^^^^^^^^^^^
>   File "F:\KeywordGacha\env\Lib\site-packages\openai\_base_client.py", line 1829, in post
>     return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "F:\KeywordGacha\env\Lib\site-packages\openai\_base_client.py", line 1523, in request
>     return await self._request(
>            ^^^^^^^^^^^^^^^^^^^^
>   File "F:\KeywordGacha\env\Lib\site-packages\openai\_base_client.py", line 1624, in _request
>     raise self._make_status_error_from_response(err.response) from None
> openai.BadRequestError: Error code: 400
> [2024-09-26 17:59:56] [DEBUG] llm_request - {'model': 'Qwen2.5-32B', 'stream': False, 'temperature': 0.05, 'top_p': 0.85, 'max_tokens': 768, 'frequency_penalty': 0, 'messages': [{'role': 'user', 'content': '你是一位文本分析和语言学专家，擅长从文本中提取关键词语，并对其词性和含义进行分析。\n请按步骤对以下文本进行总结与分析。\n\n步骤：\n1、目标词语：天海彼方。\n2、故事总结：逐句阅读所有文本，总结与目标词语相关的故事内容。\n3、词义分析：在文本中找到目标词语出现的每一个地方，结合上下文，分析其词性、语义、指代实体或概念等语言学信息。\n4、姓名判断：根据语言学知识和故事总结、词义分析的结果，对目标词语中是否包含角色、家族或生物的名称进行判断，不能确定时默认为"未知"。请注意，如果目标词语是用于描述头衔、职业、亲属关系等人物属性的词语，那么即使该词语指代一个角色、家族或生物，也应判断为"否"。\n\n文本：\n俺は自身の軽率な行動を後悔した。そして同時に天海彼方という女に対する恐怖心がさらに増した。\n「リディアちゃんと同じクラスの一年A組の天海彼方です。よろしくお願いします。夕凪先輩」\nそんなアリサを横目に俺は一年A組の天海彼方の名前を脳髄に刻み込む。\n天海彼方と名乗る一年生女子はアリサに深々と頭を下げた。\n\n回答使用中文，JSON格式，仅需要以下数据，不要添加额外的文字、说明或注释：\n{\n"summary":"<故事总结步骤的结果>",\n"analysis":"<词义分析步骤的结果>",\n"reason":"<姓名判断步骤的依据>",\n"is_name":"<姓名判断步骤的结果：是/否/未知>",\n"gender":"<性别判断的结果：男/女/未知>"\n}'}]}
> [2024-09-26 17:59:56] [DEBUG] llm_response - None
> ```

应该是只会重试三次的，不论什么理由的失败，可以发个完整的日志文件上来，晚上我看一下

**Comment by kunger97** [comment]
发生该问题的的版本是v0.5.0，使用的是自建的OpenAI兼容接口，使用微软的开发者隧道映射到公网。

问题表现：

语义分析子任务执行失败后，没有预期在三次后终止，而是继续重试。（后续404错误是我终止了微软开发者隧道导致的。）

附上完整日志

https://filego.at/bucket/2f6878a2-e876-46d6-9684-adb3583cb347

**Comment by neavo** [comment]
看了一下日志，应该是按照预期工作的，似乎并没有出现 无限重试 的问题，截至你停止应用的时间点，正在进行 语义分析 步骤的第三轮重试，我在日志中也没有找到尝试次数超过4次的词条。

目前应用的逻辑是在同一类任务完成后，统一对这一类任务中失败的条目进行重试，而非单一任务失败后就立刻重试，请确认是否是这一点影响了你对 “无限重试” 的判断。

不过你这个接口也很奇怪，前面翻译步骤是正常的，后面语义分析步骤突然就400了 。。。。
