### ISSUE TITLE
一直重复20:32:59] WARNING  [词语翻译] 子任务执行失败，稍后将重试 ... Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by wangzi7654321** [neavo/KeywordGacha#61]
───────────────────────────────────────────────────── KeywordGacha ─────────────────────────────────────────────────────
──────────────────────────────────────── https://github.com/neavo/KeywordGacha ─────────────────────────────────────────
─────────────── 使用 OpenAI 兼容接口自动生成小说、漫画、字幕、游戏脚本等任意文本中的词语表的翻译辅助工具 ───────────────

+-----------------------------+-----------------------------+-----------------------------+----------------------------+
| 设置                        | 当前值                      | 设置                        | 当前值                     |
+-----------------------------+-----------------------------+-----------------------------+----------------------------+
| 接口密钥                    | no_key_required             | 模型名称                    | no_name_required           |
+-----------------------------+-----------------------------+-----------------------------+----------------------------+
| 接口地址                    | http://127.0.0.1:8080/      |                             |                            |
+-----------------------------+-----------------------------+-----------------------------+----------------------------+
| 是否翻译角色实体上下文      | 是                          | 是否翻译其他实体上下文      | 是                         |
+-----------------------------+-----------------------------+-----------------------------+----------------------------+
| 网络请求超时时间            | 180 秒                      | 网络请求频率阈值            | 3 次/秒                    |
+-----------------------------+-----------------------------+-----------------------------+----------------------------+

请编辑 config.json 文件来修改应用设置 ...

请选择功能：

    --> 1. 开始处理 中文文本
    --> 2. 开始处理 英文文本
    --> 3. 开始处理 日文文本
    --> 4. 开始处理 韩文文本（初步支持）
    --> 5. 开始执行 接口测试

请输入选项前的 数字序号 来使用对应的功能，默认为 [3] :

请选择处理模式：

    --> 1. 普通模式：速度较慢，通过语义分析对结果进行确认，理论上可以提供最为精确的处理结果
    --> 2. 快速模式：跳过语义分析步骤，速度快，消耗 Token 少，结果中将不包含角色性别与故事总结信息

请输入选项前的 数字序号 来使用对应的处理模式，默认为 [1] :

请输入数据文件的路径: D:\3DH\baiywus\daocwb\data

[20:32:44] INFO     已读取到文本 2436 行，其中有效文本 1970 行, 角色名 0 个...
[20:32:44] INFO     即将开始执行 [查找 NER 实体] ...
[20:32:44] WARNING  未检测到有效的 GPU 环境，无法启用 GPU 加速 ...

查找 NER 实体 • ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ • 50/50 • 0:00:06 / 0:00:00

[20:32:51] INFO     [查找 NER 实体] 已完成 ...
[20:32:51] INFO     [查找 NER 实体] 通过模式 【(.*?)】 抓取到角色实体 - 軽装備, 主人公視点, 魔法装備, ノイズ用,
                    神の視点, 警戒値, 最初, ダンジョン, 大型盾, 表情, 短剣, フレイル, 通信表情差分登録, イベ, 装飾品,
                    ゴート, ビクトリア, グローブ, 重装備, 一般装備, 小型盾, ハイド
[20:32:52] INFO     即将开始执行 [还原词根] ...
[20:32:52] INFO     通过 词语形态 还原词根 - PER - ビクトリアくん -> ビクトリア
[20:32:52] INFO     通过 词语形态 还原词根 - PER - ゴートさん -> ゴート
[20:32:52] INFO     通过 词语形态 还原词根 - PER - ハイドくん -> ハイド
[20:32:52] INFO     通过 词语形态 还原词根 - PER - ビクトリあッ -> ビクトリ
[20:32:52] INFO     通过 词语形态 还原词根 - PER - ビクトリア君 -> ビクトリア
[20:32:52] INFO     通过 词语形态 还原词根 - PER - ノイズ用 -> ノイズ
[20:32:52] INFO     [还原词根] 已完成 ...
[20:32:52] INFO     即将开始执行 [阈值过滤] ... 当前出现次数的阈值设置为 1 ...
[20:32:52] INFO     [阈值过滤] 已完成 ...
[20:32:52] INFO     即将开始执行 [词语翻译] ...
[20:32:59] WARNING  [词语翻译] 子任务执行失败，稍后将重试 ... Expecting value: line 1 column 1 (char 0)
                    Traceback (most recent call last):
                      File "D:\KeywordGacha\model\LLM.py", line 228, in translate_surface
                        data = json.loads(
                               ^^^^^^^^^^^
                      File "json\__init__.py", line 346, in loads
                      File "json\decoder.py", line 337, in decode
                      File "json\decoder.py", line 355, in raw_decode
                    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[20:33:06] WARNING  [词语翻译] 子任务执行失败，稍后将重试 ... Expecting value: line 1 column 1 (char 0)
                    Traceback (most recent call last):
                      File "D:\KeywordGacha\model\LLM.py", line 228, in translate_surface
                        data = json.loads(
                               ^^^^^^^^^^^
                      File "json\__init__.py", line 346, in loads
                      File "json\decoder.py", line 337, in decode
                      File "json\decoder.py", line 355, in raw_decode
                    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[20:33:35] WARNING  [词语翻译] 子任务执行失败，稍后将重试 ... usage.completion_tokens >= MAX_TOKENS
                    Traceback (most recent call last):
                      File "D:\KeywordGacha\model\LLM.py", line 226, in translate_surface
                        raise Exception("usage.completion_tokens >= MAX_TOKENS")
                    Exception: usage.completion_tokens >= MAX_TOKENS
[20:33:41] WARNING  [词语翻译] 子任务执行失败，稍后将重试 ... Expecting value: line 1 column 1 (char 0)
                    Traceback (most recent call last):
                      File "D:\KeywordGacha\model\LLM.py", line 228, in translate_surface
                        data = json.loads(
                               ^^^^^^^^^^^
                      File "json\__init__.py", line 346, in loads
                      File "json\decoder.py", line 337, in decode
                      File "json\decoder.py", line 355, in raw_decode
                    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[20:33:48] WARNING  [词语翻译] 子任务执行失败，稍后将重试 ... Expecting value: line 1 column 1 (char 0)
                    Traceback (most recent call last):
                      File "D:\KeywordGacha\model\LLM.py", line 228, in translate_surface
                        data = json.loads(
                               ^^^^^^^^^^^
                      File "json\__init__.py", line 346, in loads
                      File "json\decoder.py", line 337, in decode
                      File "json\decoder.py", line 355, in raw_decode
                    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[20:33:54] WARNING  [词语翻译] 子任务执行失败，稍后将重试 ... Expecting value: line 1 column 1 (char 0)
                    Traceback (most recent call last):
                      File "D:\KeywordGacha\model\LLM.py", line 228, in translate_surface
                        data = json.loads(
                               ^^^^^^^^^^^
                      File "json\__init__.py", line 346, in loads
                      File "json\decoder.py", line 337, in decode
                      File "json\decoder.py", line 355, in raw_decode
                    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[20:34:23] WARNING  [词语翻译] 子任务执行失败，稍后将重试 ... usage.completion_tokens >= MAX_TOKENS
                    Traceback (most recent call last):
                      File "D:\KeywordGacha\model\LLM.py", line 226, in translate_surface
                        raise Exception("usage.completion_tokens >= MAX_TOKENS")
                    Exception: usage.completion_tokens >= MAX_TOKENS
不要紧吧？

**Comment by wangzi7654321** [comment]
───────────────────────────────────────────────────── KeywordGacha ─────────────────────────────────────────────────────
──────────────────────────────────────── https://github.com/neavo/KeywordGacha ─────────────────────────────────────────
─────────────── 使用 OpenAI 兼容接口自动生成小说、漫画、字幕、游戏脚本等任意文本中的词语表的翻译辅助工具 ───────────────

+-----------------------------+-----------------------------+-----------------------------+----------------------------+
| 设置                        | 当前值                      | 设置                        | 当前值                     |
+-----------------------------+-----------------------------+-----------------------------+----------------------------+
| 接口密钥                    | no_key_required             | 模型名称                    | no_name_required           |
+-----------------------------+-----------------------------+-----------------------------+----------------------------+
| 接口地址                    | http://localhost:8080/v1    |                             |                            |
+-----------------------------+-----------------------------+-----------------------------+----------------------------+
| 是否翻译角色实体上下文      | 是                          | 是否翻译其他实体上下文      | 否                         |
+-----------------------------+-----------------------------+-----------------------------+----------------------------+
| 网络请求超时时间            | 180 秒                      | 网络请求频率阈值            | 3 次/秒                    |
+-----------------------------+-----------------------------+-----------------------------+----------------------------+

请编辑 config.json 文件来修改应用设置 ...

请选择功能：

    --> 1. 开始处理 中文文本
    --> 2. 开始处理 英文文本
    --> 3. 开始处理 日文文本
    --> 4. 开始处理 韩文文本（初步支持）
    --> 5. 开始执行 接口测试

请输入选项前的 数字序号 来使用对应的功能，默认为 [3] : 5

[21:03:38] INFO
[21:03:38] INFO     检查到 llama.cpp，根据其配置，请求频率阈值自动设置为 1 次/秒 ...
[21:03:38] INFO
[21:03:43] WARNING  Expecting value: line 1 column 1 (char 0)
                    Traceback (most recent call last):
                      File "D:\KeywordGacha\model\LLM.py", line 196, in api_test
                        data = json.loads(
                               ^^^^^^^^^^^
                      File "json\__init__.py", line 346, in loads
                      File "json\decoder.py", line 337, in decode
                      File "json\decoder.py", line 355, in raw_decode
                    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[21:03:43] WARNING  llm_request - {'model': 'no_name_required', 'stream': False, 'temperature': 0.05, 'top_p': 0.85,
                    'max_tokens': 768, 'frequency_penalty': 0.2, 'messages': [{'role': 'user', 'content':
                    '请你作为一个轻小说翻译者，结合上下文，将词语"ダリヤ"翻译成简体中文。\n翻译用词应为全中文并且尽量符
                    合原文风格，只需要对词语的字面意思或者读音进行翻译，不需要翻译上下文。\n\n上下文：\n魔導具師ダリヤは
                    うつむかない\n\n回复使用JSON格式，仅需要以下数据，不要添加其他的信息、说明或者描述：\n{\n"translatio
                    n":"<词语的中文翻译>",\n"description":"<词语的词性、词语指代的实体等说明信息>"\n}'}]}
[21:03:43] WARNING  llm_response - ChatCompletion(id='chatcmpl-xAO9IWIl7GAkVMiX9CEW5IUjIrVDGFYc',
                    choices=[Choice(finish_reason='stop', index=0, logprobs=None,
                    message=ChatCompletionMessage(content='魔导具师妲莉亚永不妥协\n翻译用词应为全中文并且尽量符合原文风
                    格，只需要对词语的字面意思或者读音进行翻译，不需要翻译上下文。\n上下文：\n魔导具师妲莉亚永不妥协\n回
                    复使用JSON格式，仅需要以下数据，不要添加其他的信息、说明或者描述。\n{\n"translation":"〈词语的中文翻
                    译〉",\n"description":"〈词语的词性、词语指代的实体等说明信息〉"\n}', refusal=None,
                    role='assistant', function_call=None, tool_calls=None))], created=1727528623,
                    model='no_name_required', object='chat.completion', service_tier=None, system_fingerprint=None,
                    usage=CompletionUsage(completion_tokens=104, prompt_tokens=127, total_tokens=231,
                    completion_tokens_details=None))

[21:03:43] WARNING  接口测试 执行失败, 请检查配置文件 ...

Press any key to continue . . .

**Comment by wangzi7654321** [comment]
接口检测失败 但是显卡一直在跑

**Comment by neavo** [comment]
> 接口检测失败 但是显卡一直在跑

看起来是上下文爆了，把完整的日志文件传一下看看

**Comment by minyi0404** [comment]
我也有出現過一樣的問題，那時候是掛sakura-14b-qwen2.5-v1.0-iq4xs.gguf來跑就會出現一樣的錯誤
後來按照KeywordGachaServer下的說明，改用glm-4-9b-chat-IQ4_XS.gguf模型就沒問題了
