### ISSUE TITLE
GPT请求报错ERR400

### ISSUE THREAD

**Issue by steamqaqwq** [neavo/KeywordGacha#82]
使用GPT接口报错err400，后面换了claude没问题...
```
[2024-12-31 03:06:30] [WARNING] [词义分析] 子任务执行失败，稍后将重试 ... Error code: 400 - {'error': {'message': "Setting 'max_tokens' and 'max_completion_tokens' at the same time is not supported.  (request id: 2024123103062962320720267438851)", 'type': 'invalid_request_error', 'param': 'max_tokens', 'code': 'invalid_parameter_combination'}}
Traceback (most recent call last):
  File "C:\Temp\KeywordGacha\model\LLM.py", line 228, in surface_analysis
    raise error
  File "C:\Temp\KeywordGacha\model\LLM.py", line 140, in do_request
    completion = await self.client.chat.completions.create(**llm_request)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Temp\KeywordGacha\env\Lib\site-packages\openai\resources\chat\completions.py", line 1720, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
  File "C:\Temp\KeywordGacha\env\Lib\site-packages\openai\_base_client.py", line 1843, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Temp\KeywordGacha\env\Lib\site-packages\openai\_base_client.py", line 1537, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Temp\KeywordGacha\env\Lib\site-packages\openai\_base_client.py", line 1638, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': "Setting 'max_tokens' and 'max_completion_tokens' at the same time is not supported.  (request id: 2024123103062962320720267438851)", 'type': 'invalid_request_error', 'param': 'max_tokens', 'code': 'invalid_parameter_combination'}}
[2024-12-31 03:06:30] [DEBUG] llm_request - {'model': 'gpt-4o-mini-2024-07-18', 'stream': False, 'temperature': 0.05, 'top_p': 0.85, 'max_tokens': 768, 'max_completion_tokens': 768, 'frequency_penalty': 0, 'messages': [{'role': 'system', 'content': '你是游戏文本分析与翻译的专家，请对参考文本进行分析，然后将目标词语翻译成简体中文。\n分析步骤：\n1、故事梗概：总结与目标词语相关的故事内容。\n2、特征分析：分析目标词语的词性、指代的实体等语言学特征。\n3、实体类型判断：从以下候选项目中判断目标词语指代的实体类型，超出候选范围或无法确定时视为"无法判断"：姓名、家族、地点、组织、物品、事件。\n4、性别判断：从以下候选项目中判断目标词语指代对象的性别，超出候选范围或无法确定时视为"无法判断"：男、女。\n翻译要求：\n1、只需翻译目标词语，不需要翻译参考文本中的其他内容。\n2、翻译结果需全部为简体中文，且尽量保留原文风格特点。\n3、即使目标词语在参考文本中出现多次，也只需翻译一次。\n回答使用中文，严格按照以下JSON格式返回，不要添加额外的文字、说明或注释：\n{\n"summary":"<故事梗概>",\n"analysis":"<特征分析>",\n"entity_type":"<实体类型:姓名/家族/地点/组织/物品/事件/无法判断>",\n"gender":"<性别判断:男/女/无法判断>",\n"translation":"<翻译结果>"\n}'}, {'role': 'user', 'content': '目标词语：竜属性強化\n参考文本：\n【竜殺】【??】まほう+50【竜属性耐性】【滅竜属性強化】竜を滅ぼすために作られた禁断の魔法剣。\n【竜殺】【??】まほう+50【竜属性耐性】【滅竜属性強化】\n【竜属性強化】【闇属性強化】【闇属性強化】\n竜属性強化、こうげき・まほう・はやさ↑\n(全)竜属性強化 こうげき↑ぼうぎょ↓\n【炎属性強化】【竜属性強化】\n【竜属性強化】【竜属性強化】\n词语原文 : 滅竜属性強化\n词语原文 : 竜属性強化\n【竜属性強化・極】\n【竜属性強化】\n竜属性強化'}]}
[2024-12-31 03:06:30] [DEBUG] llm_response - None
[2024-12-31 03:06:31] [WARNING] [词义分析] 子任务执行失败，稍后将重试 ... Error code: 400 - {'error': {'message': "Setting 'max_tokens' and 'max_completion_tokens' at the same time is not supported.  (request id: 2024123103062996207361091293447)", 'type': 'invalid_request_error', 'param': 'max_tokens', 'code': 'invalid_parameter_combination'}}
Traceback (most recent call last):

```

**Comment by neavo** [comment]
> 使用GPT接口报错err400，后面换了claude没问题...
> 
> ```
> [2024-12-31 03:06:30] [WARNING] [词义分析] 子任务执行失败，稍后将重试 ... Error code: 400 - {'error': {'message': "Setting 'max_tokens' and 'max_completion_tokens' at the same time is not supported.  (request id: 2024123103062962320720267438851)", 'type': 'invalid_request_error', 'param': 'max_tokens', 'code': 'invalid_parameter_combination'}}
> Traceback (most recent call last):
>   File "C:\Temp\KeywordGacha\model\LLM.py", line 228, in surface_analysis
>     raise error
>   File "C:\Temp\KeywordGacha\model\LLM.py", line 140, in do_request
>     completion = await self.client.chat.completions.create(**llm_request)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Temp\KeywordGacha\env\Lib\site-packages\openai\resources\chat\completions.py", line 1720, in create
>     return await self._post(
>            ^^^^^^^^^^^^^^^^^
>   File "C:\Temp\KeywordGacha\env\Lib\site-packages\openai\_base_client.py", line 1843, in post
>     return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Temp\KeywordGacha\env\Lib\site-packages\openai\_base_client.py", line 1537, in request
>     return await self._request(
>            ^^^^^^^^^^^^^^^^^^^^
>   File "C:\Temp\KeywordGacha\env\Lib\site-packages\openai\_base_client.py", line 1638, in _request
>     raise self._make_status_error_from_response(err.response) from None
> openai.BadRequestError: Error code: 400 - {'error': {'message': "Setting 'max_tokens' and 'max_completion_tokens' at the same time is not supported.  (request id: 2024123103062962320720267438851)", 'type': 'invalid_request_error', 'param': 'max_tokens', 'code': 'invalid_parameter_combination'}}
> [2024-12-31 03:06:30] [DEBUG] llm_request - {'model': 'gpt-4o-mini-2024-07-18', 'stream': False, 'temperature': 0.05, 'top_p': 0.85, 'max_tokens': 768, 'max_completion_tokens': 768, 'frequency_penalty': 0, 'messages': [{'role': 'system', 'content': '你是游戏文本分析与翻译的专家，请对参考文本进行分析，然后将目标词语翻译成简体中文。\n分析步骤：\n1、故事梗概：总结与目标词语相关的故事内容。\n2、特征分析：分析目标词语的词性、指代的实体等语言学特征。\n3、实体类型判断：从以下候选项目中判断目标词语指代的实体类型，超出候选范围或无法确定时视为"无法判断"：姓名、家族、地点、组织、物品、事件。\n4、性别判断：从以下候选项目中判断目标词语指代对象的性别，超出候选范围或无法确定时视为"无法判断"：男、女。\n翻译要求：\n1、只需翻译目标词语，不需要翻译参考文本中的其他内容。\n2、翻译结果需全部为简体中文，且尽量保留原文风格特点。\n3、即使目标词语在参考文本中出现多次，也只需翻译一次。\n回答使用中文，严格按照以下JSON格式返回，不要添加额外的文字、说明或注释：\n{\n"summary":"<故事梗概>",\n"analysis":"<特征分析>",\n"entity_type":"<实体类型:姓名/家族/地点/组织/物品/事件/无法判断>",\n"gender":"<性别判断:男/女/无法判断>",\n"translation":"<翻译结果>"\n}'}, {'role': 'user', 'content': '目标词语：竜属性強化\n参考文本：\n【竜殺】【??】まほう+50【竜属性耐性】【滅竜属性強化】竜を滅ぼすために作られた禁断の魔法剣。\n【竜殺】【??】まほう+50【竜属性耐性】【滅竜属性強化】\n【竜属性強化】【闇属性強化】【闇属性強化】\n竜属性強化、こうげき・まほう・はやさ↑\n(全)竜属性強化 こうげき↑ぼうぎょ↓\n【炎属性強化】【竜属性強化】\n【竜属性強化】【竜属性強化】\n词语原文 : 滅竜属性強化\n词语原文 : 竜属性強化\n【竜属性強化・極】\n【竜属性強化】\n竜属性強化'}]}
> [2024-12-31 03:06:30] [DEBUG] llm_response - None
> [2024-12-31 03:06:31] [WARNING] [词义分析] 子任务执行失败，稍后将重试 ... Error code: 400 - {'error': {'message': "Setting 'max_tokens' and 'max_completion_tokens' at the same time is not supported.  (request id: 2024123103062996207361091293447)", 'type': 'invalid_request_error', 'param': 'max_tokens', 'code': 'invalid_parameter_combination'}}
> Traceback (most recent call last):
> ```

收到，下个版本修

**Comment by neavo** [comment]
> 使用GPT接口报错err400，后面换了claude没问题...
> 
> ```
> [2024-12-31 03:06:30] [WARNING] [词义分析] 子任务执行失败，稍后将重试 ... Error code: 400 - {'error': {'message': "Setting 'max_tokens' and 'max_completion_tokens' at the same time is not supported.  (request id: 2024123103062962320720267438851)", 'type': 'invalid_request_error', 'param': 'max_tokens', 'code': 'invalid_parameter_combination'}}
> Traceback (most recent call last):
>   File "C:\Temp\KeywordGacha\model\LLM.py", line 228, in surface_analysis
>     raise error
>   File "C:\Temp\KeywordGacha\model\LLM.py", line 140, in do_request
>     completion = await self.client.chat.completions.create(**llm_request)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Temp\KeywordGacha\env\Lib\site-packages\openai\resources\chat\completions.py", line 1720, in create
>     return await self._post(
>            ^^^^^^^^^^^^^^^^^
>   File "C:\Temp\KeywordGacha\env\Lib\site-packages\openai\_base_client.py", line 1843, in post
>     return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Temp\KeywordGacha\env\Lib\site-packages\openai\_base_client.py", line 1537, in request
>     return await self._request(
>            ^^^^^^^^^^^^^^^^^^^^
>   File "C:\Temp\KeywordGacha\env\Lib\site-packages\openai\_base_client.py", line 1638, in _request
>     raise self._make_status_error_from_response(err.response) from None
> openai.BadRequestError: Error code: 400 - {'error': {'message': "Setting 'max_tokens' and 'max_completion_tokens' at the same time is not supported.  (request id: 2024123103062962320720267438851)", 'type': 'invalid_request_error', 'param': 'max_tokens', 'code': 'invalid_parameter_combination'}}
> [2024-12-31 03:06:30] [DEBUG] llm_request - {'model': 'gpt-4o-mini-2024-07-18', 'stream': False, 'temperature': 0.05, 'top_p': 0.85, 'max_tokens': 768, 'max_completion_tokens': 768, 'frequency_penalty': 0, 'messages': [{'role': 'system', 'content': '你是游戏文本分析与翻译的专家，请对参考文本进行分析，然后将目标词语翻译成简体中文。\n分析步骤：\n1、故事梗概：总结与目标词语相关的故事内容。\n2、特征分析：分析目标词语的词性、指代的实体等语言学特征。\n3、实体类型判断：从以下候选项目中判断目标词语指代的实体类型，超出候选范围或无法确定时视为"无法判断"：姓名、家族、地点、组织、物品、事件。\n4、性别判断：从以下候选项目中判断目标词语指代对象的性别，超出候选范围或无法确定时视为"无法判断"：男、女。\n翻译要求：\n1、只需翻译目标词语，不需要翻译参考文本中的其他内容。\n2、翻译结果需全部为简体中文，且尽量保留原文风格特点。\n3、即使目标词语在参考文本中出现多次，也只需翻译一次。\n回答使用中文，严格按照以下JSON格式返回，不要添加额外的文字、说明或注释：\n{\n"summary":"<故事梗概>",\n"analysis":"<特征分析>",\n"entity_type":"<实体类型:姓名/家族/地点/组织/物品/事件/无法判断>",\n"gender":"<性别判断:男/女/无法判断>",\n"translation":"<翻译结果>"\n}'}, {'role': 'user', 'content': '目标词语：竜属性強化\n参考文本：\n【竜殺】【??】まほう+50【竜属性耐性】【滅竜属性強化】竜を滅ぼすために作られた禁断の魔法剣。\n【竜殺】【??】まほう+50【竜属性耐性】【滅竜属性強化】\n【竜属性強化】【闇属性強化】【闇属性強化】\n竜属性強化、こうげき・まほう・はやさ↑\n(全)竜属性強化 こうげき↑ぼうぎょ↓\n【炎属性強化】【竜属性強化】\n【竜属性強化】【竜属性強化】\n词语原文 : 滅竜属性強化\n词语原文 : 竜属性強化\n【竜属性強化・極】\n【竜属性強化】\n竜属性強化'}]}
> [2024-12-31 03:06:30] [DEBUG] llm_response - None
> [2024-12-31 03:06:31] [WARNING] [词义分析] 子任务执行失败，稍后将重试 ... Error code: 400 - {'error': {'message': "Setting 'max_tokens' and 'max_completion_tokens' at the same time is not supported.  (request id: 2024123103062996207361091293447)", 'type': 'invalid_request_error', 'param': 'max_tokens', 'code': 'invalid_parameter_combination'}}
> Traceback (most recent call last):
> ```

新版已修，请确认

**Comment by steamqaqwq** [comment]
新版已测试没问题，感谢作者
